### ISSUE TITLE
1.5 very unstable, "restore volume at launch" and "disable_donate" likely culprits

### ISSUE THREAD

**Issue by Jerrk** [Frosthaven/voicemeeter-windows-volume#5]
1.4.2 works as normal with no issues.

i've tried multiple configurations with toggles of true/false in the settings.json file, but it seems to only launch reliably with no changes done from the default settings.json.

sometimes it wont laucnh while voicemeeter is running and i have to shut it down before opening VWV.

![](https://i.imgur.com/eNydAQh.gif)

"restore volume at launch" toggle seems to very reliably always crash, i am sometimes able to enable all other options but that one before it crashes.

Manually editing disable_donate to true also seems to always reliably crash as well.
###### also i prefer the old icon :eyes:

**Comment by Frosthaven** [comment]
Thanks for this report! Seriously saved a lot of wasted downloads. I've removed the offending release! If you run into issues let me know - I found the root cause of those two settings causing failure.

As for the icon, I hear you! If you want to open a ticket for icon design ill be happy to participate!

**Comment by Jerrk** [comment]
thanks for the quick fix :grin:
